FROM node:22-alpine AS builder

WORKDIR /app

# Install dependencies
COPY package.json ./
RUN npm install

# Copy source INCLUDING .env.prod
COPY . .

# Build using prod env
RUN npm run build:prod


FROM node:22-alpine

WORKDIR /app

# Copy full app like dev (same behavior)
COPY --from=builder /app ./

ENV NODE_ENV=production

EXPOSE 3000

CMD ["npm", "run", "start"]
