# ---------- Builder ----------
FROM node:22-alpine AS builder

WORKDIR /app

# Install dependencies
COPY package.json package-lock.json ./
RUN npm install

# Copy source including env files
COPY . .

# Build using production environment
RUN npm run build:prod


# ---------- Runner ----------
FROM node:22-alpine

WORKDIR /app

# Copy built app from builder
COPY --from=builder /app ./

ENV NODE_ENV=production

EXPOSE 3000

CMD ["npm", "run", "start"]
