FROM node:22-alpine AS builder

WORKDIR /app

COPY package.json ./

RUN npm install

COPY . .

RUN npm run build:prod


FROM node:22-alpine

WORKDIR /app

COPY --from=builder /app ./

RUN npm install

ENV NODE_ENV=production

EXPOSE 3000

CMD ["npm", "run", "start"]
