export default function Agent1() {
  return (
    <div className="sub-section">
      <h2>1.YOUR OBLIGATIONS</h2>
      <h3>Obligations and Conditions for Using Ride.Rent Platform</h3>
      <p>
        As a user of the Ride.Rent platform, you must adhere to the following
        obligations and conditions:
      </p>
      <br />
      <ol>
        <li>
          <strong>Advertising Standards:</strong>
          <ul className="list-disc pl-6">
            <li>
              You may only advertise goods and services that are currently
              available for purchase, rent, or lease.
            </li>
            <li>
              You must hold a valid trade license in the United Arab Emirates.
            </li>
            <br />
          </ul>
        </li>
        <li>
          <strong>Prohibited Actions:</strong>
          <ul>
            <li>
              Do not make, arrange, or authorize the insertion of any reference
              to Emirates or countries not permitted by your subscription.
            </li>
            <li>
              Do not use the Platform for improper purposes, including posting
              defamatory, misleading, or deceptive information, infringing
              copyrights, or engaging in activities that could expose us to
              liability or legal proceedings.
            </li>
          </ul>
          <br />
        </li>
        <li>
          <strong>Use of Our Platform:</strong>
          <ul>
            <li>
              You may not reference Ride.Rent or its Platform in any document
              &#40;including promotional or merchandising material&#41; or on
              any website other than our Platform without prior written consent.
            </li>
            <li>
              Comply with all applicable rules and regulations related to
              electronic transactions.
            </li>
            <li>
              Adhere to guidelines and codes issued by the RTA or other local
              regulatory authorities.
            </li>
          </ul>
          <br />
        </li>
        <li>
          <strong>Service Compliance:</strong>
          <ul>
            <li>
              Provide the goods and services as specified in the Ride.Rent
              confirmation email presented by the customer. Failure to do so may
              result in a loss of payment and a refund to the customer.
            </li>
            <li>
              Ensure your use of the Service complies with all applicable laws.
            </li>
          </ul>
          <br />
        </li>
        <li>
          <strong>Accuracy and Responsibility:</strong>
          <ul>
            <li>
              You are responsible for the accuracy and completeness of any
              material submitted through the Service.
            </li>
            <li>
              Ensure no unauthorized person uses your subscription to the
              Service in breach of these terms and conditions.
            </li>
          </ul>
          <br />
        </li>
        <li>
          <strong>Acknowledgments:</strong>
          <ul>
            <li>
              You have read and agree to be bound by the terms of all legal
              notices posted on the Platform.
            </li>
            <li>
              You represent and warrant that you are authorized to make
              available the material generated or submitted through the Service.
            </li>
          </ul>
          <br />
        </li>
        <li>
          <strong>Intellectual Property and Licensing:</strong>
          <ul>
            <li>
              By using the Service, you grant us an irrevocable, worldwide,
              royalty-free license to commercialize, copy, license to other
              persons, use, and adapt for any purpose any material you generate
              or submit to make use of the Service.
            </li>
          </ul>
          <br />
        </li>
        <li>
          <strong>Monitoring and Responsibility:</strong>
          <ul>
            <li>
              We are not obligated to monitor or censor material generated by
              users of the Service, but we reserve the right to do so.
            </li>
            <li>
              We are not responsible for the Service&apos;s content or for any
              errors or omissions in the data provided.
            </li>
          </ul>
          <br />
        </li>
        <li>
          <strong>Technical and Communication Costs:</strong>
          <ul>
            <li>
              You are responsible for all telecommunications and Internet access
              charges incurred when using our Platform.
            </li>
            <li>
              You are responsible for the security and integrity of your data.
            </li>
          </ul>
          <br />
        </li>
        <li>
          <strong>Service Interruptions:</strong>
          <ul>
            <li>
              Transmission of data over the Internet can be subject to errors
              and delays.
            </li>
            <li>
              We will contact you occasionally to inform you of opportunities,
              products, and services offered by us and our business partners.
              You authorize us to contact you via email, SMS, MMS, and other
              electronic media unless you explicitly request otherwise.
            </li>
          </ul>
          <br />
        </li>
        <li>
          <strong>
            Agreement Term, Suspension, or Termination of Service:
          </strong>
          <ul>
            <li>
              This Agreement has a term of twelve &#40;12&#41; months from the
              start date specified in the Advertising Agreement. After the term
              expires, the Agreement will expire unless renewed.
            </li>
            <li>
              We may terminate this Agreement at any time for any reason with
              thirty &#40;30&#41; days&apos; written notice. If you continue to
              use the Service following termination, you remain liable for any
              incurred costs.
            </li>
            <li>
              We may immediately suspend or temporarily remove any advertisement
              uploaded by you or terminate this Agreement if you fail to pay any
              fees or charges due, breach any part of this Agreement and fail to
              rectify it within seven &#40;7&#41; days, provide false or
              misleading material, become insolvent, or undergo bankruptcy,
              liquidation, administration, or receivership.
            </li>
          </ul>
          <br />
        </li>
        <li>
          <strong>Obligations and Liabilities:</strong>
          <ul>
            <li>
              Termination of this Agreement does not relieve you of your
              obligations and liabilities under the Agreement. We reserve the
              right to enforce such obligations and liabilities in any event.
            </li>
          </ul>
          <br />
        </li>
        <li>
          <strong>Promotional Communications:</strong>
          <ul>
            <li>
              In alignment with our commitment to providing you with relevant
              updates and business opportunities, Ride.Rent may periodically
              reach out to you regarding our services, products, and offerings,
              as well as those of our strategic business partners. These
              communications may be delivered through various channels,
              including email, SMS, MMS, phone calls, or other electronic media.
              By engaging with our services, you acknowledge and agree to
              receive such communications as part of our ongoing business
              relationship.
            </li>
          </ul>
          <br />
        </li>
      </ol>
    </div>
  );
}