import './globals.scss'
import { AppProvider } from '@/context/AppContext'
import { ReactQueryProvider } from '@/utils/ReactQueryProvider'
import type { Metadata } from 'next'
import { Fira_Sans } from 'next/font/google'

export const metadata: Metadata = {
  title: 'Ride.Rent',
  description: 'Generated by create next app',
}

const firaSans = Fira_Sans({
  subsets: ['latin'],
  weight: ['300', '400', '500', '600', '700', '800', '900'],
  style: ['normal', 'italic'],
})

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={firaSans.className}>
        <ReactQueryProvider>
          <AppProvider>
            <main className="mt-[4.85rem]">{children}</main>
          </AppProvider>
        </ReactQueryProvider>
      </body>
    </html>
  )
}
