export const ENV = {
  APP_ENV: process.env.APP_ENV,
  NEXT_PUBLIC_APP_ENV: process.env.NEXT_PUBLIC_APP_ENV,

  NEXT_PUBLIC_AUTH_API_URL: process.env.NEXT_PUBLIC_AUTH_API_URL,
  API_URL: process.env.API_URL,
  NEXT_PUBLIC_API_URL: process.env.NEXT_PUBLIC_API_URL,
  API_URL_INDIA: process.env.API_URL_INDIA,
  NEXT_PUBLIC_API_URL_INDIA: process.env.NEXT_PUBLIC_API_URL_INDIA,
  ASSETS_URL: process.env.ASSETS_URL || process.env.NEXT_PUBLIC_ASSETS_URL,

  NEXT_PUBLIC_ASSETS_URL: process.env.NEXT_PUBLIC_ASSETS_URL,
  ASSETS_URL_INDIA:
    process.env.ASSETS_URL_INDIA || process.env.NEXT_PUBLIC_ASSETS_URL_INDIA,
  NEXT_PUBLIC_ASSETS_URL_INDIA: process.env.NEXT_PUBLIC_ASSETS_URL_INDIA,

  SITE_URL: process.env.SITE_URL,
  NEXT_PUBLIC_SITE_URL: process.env.NEXT_PUBLIC_SITE_URL,
  // Multi-country API configuration
  ENABLE_MULTI_COUNTRY_API: true,
  NEXT_PUBLIC_ENABLE_MULTI_COUNTRY_API: true,
  // ENABLE_MULTI_COUNTRY_API: process.env.ENABLE_MULTI_COUNTRY_API === 'true' || process.env.NEXT_PUBLIC_ENABLE_MULTI_COUNTRY_API === 'true',
  // NEXT_PUBLIC_ENABLE_MULTI_COUNTRY_API: process.env.NEXT_PUBLIC_ENABLE_MULTI_COUNTRY_API === 'true',
};
