export default function Agent3() {
  return (
    <div className="sub-section">
      <h2>3. LIMITATION OF LIABILITY AND INDEMNITY</h2>
      <p>
        To the extent permitted by the laws of the United Arab Emirates,
        Ride.Rent excludes all conditions and warranties implied into this
        Agreement and limits our liability for any consequential, special, or
        indirect loss or damage, including but not limited to loss of
        opportunity, revenue, and profits. Our liability for any breach of
        condition or warranty that cannot be excluded is limited to either
        resupplying the service or paying the cost of having the service
        resupplied. For any other claims related to this Agreement, whether
        based on contract, tort &#40;including negligence&#41;, or statute, our
        liability is capped at the amount paid to us by you under this
        Agreement. Ride.Rent is not liable for any breaches caused by your
        obligations under this Agreement or for delays and breaches arising from
        matters beyond our control, such as viruses, other defects, or server
        failures.
      </p>
      <p>
        You agree to indemnify Ride.Rent and our officers, employees, and agents
        &#40;those indemnified&#41; against any direct or consequential
        liabilities, losses, damages, expenses, and costs &#40;including legal
        expenses&#41; incurred by any of those indemnified as a result of any
        claim or proceedings brought by a third party in connection with any
        material generated by you in relation to the Service.
      </p>
      <br />
      <p>
        Ride.Rent reserves the right to change these Terms and Conditions at any
        time, with or without 30 days&apos; prior written notice. Publishing the
        amended version on our Platform constitutes written notice to you of
        such changes. No delay or failure by Ride.Rent to enforce any provision
        of this Agreement will be deemed a waiver, create a precedent, or
        prejudice our rights. Notices must be sent by email, prepaid post, or
        facsimile to your or our last known address. You must not assign this
        Agreement without our written consent. This Agreement, together with any
        documents referred to in it or provided by us at the same time,
        constitutes the entire agreement between us and supersedes all prior
        understandings, agreements, or representations. The laws of the United
        Arab Emirates govern this Agreement. If any term of this Agreement is,
        or may become, invalid or unenforceable at law, the validity and
        enforceability of the remainder will not be affected.
      </p>
    </div>
  )
}
